# Generated by Django 2.2.10 on 2021-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('place', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='static/images/services/')),
                ('comment', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='static/images/services/')),
                ('comment', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
