# Generated by Django 2.2.10 on 2021-06-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210606_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
