# Generated by Django 2.2.10 on 2021-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210607_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='name',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='name',
            field=models.CharField(max_length=42),
        ),
    ]
