# Generated by Django 2.2.10 on 2021-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210607_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='comment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comment',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
