# Generated by Django 2.2.10 on 2021-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20210607_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(blank=True, max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
