# Generated by Django 2.2.10 on 2021-06-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20210607_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
