# Generated by Django 2.2.10 on 2021-06-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20210607_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciosistema',
            name='capacity',
        ),
        migrations.DeleteModel(
            name='Capacidad',
        ),
    ]
